/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mini_room_art_copy.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, OrthographicCamera } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Room2(props) {
  const { scene } = useGLTF('/models/mini_room_art_copy.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[54.843, 266.823, -4.66]} scale={1.738}>
          <group position={[-45.753, -283.032, 87.455]} rotation={[0.312, -0.2, 0.488]} scale={[-1.197, 1.197, 1.197]}>
            <mesh geometry={nodes.Cylinder_3_3.geometry} material={nodes.Cylinder_3_3.material} position={[-2.989, 24.835, -28.736]} rotation={[-Math.PI / 9, 0, 0.087]} scale={0.653} />
            <mesh geometry={nodes.Torus_5.geometry} material={nodes.Torus_5.material} position={[0.001, 4.97, -18.704]} rotation={[-2.337, 0, 2.356]} />
            <mesh geometry={nodes.Torus_4.geometry} material={nodes.Torus_4.material} position={[0.001, 0.777, -15.379]} rotation={[-2.337, 0, 2.356]} />
            <mesh geometry={nodes.Torus_3.geometry} material={nodes.Torus_3.material} position={[0.001, -2.434, -11.251]} rotation={[-2.337, 0, 2.356]} />
            <mesh geometry={nodes.Torus_2.geometry} material={nodes.Torus_2.material} position={[0.001, -4.821, -6.388]} rotation={[-2.337, 0, 2.356]} />
            <mesh geometry={nodes.Torus.geometry} material={nodes.Torus.material} position={[0.001, -6.167, -0.327]} rotation={[-2.337, 0, 2.356]} />
            <mesh geometry={nodes.Rectangle_5_4.geometry} material={nodes.Rectangle_5_4.material} position={[11.671, -14.093, 13.971]} rotation={[-Math.PI / 2, 1.484, Math.PI / 9]} />
            <mesh geometry={nodes.Rectangle_4_1.geometry} material={nodes.Rectangle_4_1.material} position={[11.45, -11.573, 5.143]} rotation={[-Math.PI / 2, 1.484, Math.PI / 9]} />
            <mesh geometry={nodes.Rectangle_3_4.geometry} material={nodes.Rectangle_3_4.material} position={[11.288, -9.717, -3.391]} rotation={[-Math.PI / 2, 1.484, Math.PI / 9]} />
            <mesh geometry={nodes.Cube_2_5.geometry} material={nodes.Cube_2_5.material} position={[-0.123, -11.499, 2.05]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Rectangle_2_4.geometry} material={nodes.Rectangle_2_4.material} position={[-0.006, -27.499, 0.541]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-99.24, -294.464, 140.868]} rotation={[-0.087, -Math.PI / 6, -0.175]} scale={1.197}>
            <mesh geometry={nodes.Cylinder_3_4.geometry} material={nodes.Cylinder_3_4.material} position={[-0.072, 25.369, -26.102]} rotation={[-0.175, 0, 0]} scale={0.653} />
            <mesh geometry={nodes.Torus_5_1.geometry} material={nodes.Torus_5_1.material} position={[0.001, 4.97, -18.704]} rotation={[-2.337, 0, 2.356]} />
            <mesh geometry={nodes.Torus_4_1.geometry} material={nodes.Torus_4_1.material} position={[0.001, 0.777, -15.379]} rotation={[-2.337, 0, 2.356]} />
            <mesh geometry={nodes.Torus_3_1.geometry} material={nodes.Torus_3_1.material} position={[0.001, -2.434, -11.251]} rotation={[-2.337, 0, 2.356]} />
            <mesh geometry={nodes.Torus_2_1.geometry} material={nodes.Torus_2_1.material} position={[0.001, -4.821, -6.388]} rotation={[-2.337, 0, 2.356]} />
            <mesh geometry={nodes.Torus_1.geometry} material={nodes.Torus_1.material} position={[0.001, -6.167, -0.327]} rotation={[-2.337, 0, 2.356]} />
            <mesh geometry={nodes.Rectangle_5_5.geometry} material={nodes.Rectangle_5_5.material} position={[11.671, -14.093, 13.971]} rotation={[-Math.PI / 2, 1.484, Math.PI / 9]} />
            <mesh geometry={nodes.Rectangle_4_2.geometry} material={nodes.Rectangle_4_2.material} position={[11.45, -11.573, 5.143]} rotation={[-Math.PI / 2, 1.484, Math.PI / 9]} />
            <mesh geometry={nodes.Rectangle_3_5.geometry} material={nodes.Rectangle_3_5.material} position={[11.288, -9.717, -3.391]} rotation={[-Math.PI / 2, 1.484, Math.PI / 9]} />
            <mesh geometry={nodes.Cube_2_6.geometry} material={nodes.Cube_2_6.material} position={[-0.123, -11.499, 2.05]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Rectangle_2_5.geometry} material={nodes.Rectangle_2_5.material} position={[-0.006, -27.499, 0.541]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[31.882, 137.509, -80.185]} rotation={[-1.13, -0.241, -0.469]} scale={0.586}>
            <group position={[-58.298, -62.561, 1.558]} rotation={[Math.PI / 2, -1.396, -Math.PI / 2]} scale={0.7}>
              <mesh geometry={nodes.Rectangle_3_7.geometry} material={nodes.Rectangle_3_7.material} position={[-1.204, -0.119, 15.358]} />
              <mesh geometry={nodes.Rectangle_2_8.geometry} material={nodes.Rectangle_2_8.material} position={[-1.204, -0.119, 8.505]} />
              <mesh geometry={nodes.Cube_18.geometry} material={nodes.Cube_18.material} position={[0, 0, -7.358]} />
            </group>
            <group position={[55.954, -61.834, 1.78]} rotation={[Math.PI / 2, 1.484, -Math.PI / 2]} scale={0.7}>
              <mesh geometry={nodes.Rectangle_3_8.geometry} material={nodes.Rectangle_3_8.material} position={[-1.204, -0.119, 15.358]} />
              <mesh geometry={nodes.Rectangle_2_9.geometry} material={nodes.Rectangle_2_9.material} position={[-1.204, -0.119, 8.505]} />
              <mesh geometry={nodes.Cube_19.geometry} material={nodes.Cube_19.material} position={[0, 0, -7.358]} />
            </group>
            <mesh geometry={nodes.Cylinder_2_2.geometry} material={nodes.Cylinder_2_2.material} position={[-76.467, -48.31, 2.681]} rotation={[0, 0, 0.262]} />
            <mesh geometry={nodes.Cylinder_8.geometry} material={nodes.Cylinder_8.material} position={[72.074, -48.408, 2.681]} rotation={[0, 0, -0.175]} />
            <mesh geometry={nodes.Torus_6.geometry} material={nodes.Torus_6.material} position={[-2.41, -33.305, 1.834]} rotation={[0, 0, -Math.PI / 2]} scale={[1.054, 1, 1]} />
          </group>
          <group position={[17.295, -213.495, -71.278]} rotation={[0, -Math.PI / 6, 0]}>
            <mesh geometry={nodes.Cube_9_1.geometry} material={nodes.Cube_9_1.material} position={[-2.31, 98.833, -2.38]} rotation={[Math.PI / 2, 0, Math.PI / 4]} />
            <mesh geometry={nodes.Cube_8_1.geometry} material={nodes.Cube_8_1.material} position={[-2.38, 97.156, 2.31]} rotation={[Math.PI / 2, 0, -Math.PI / 4]} />
            <mesh geometry={nodes.Cylinder_6_1.geometry} material={nodes.Cylinder_6_1.material} position={[67.316, -2.732, 67.271]} rotation={[1.396, -1.484, 1.484]} scale={1.241} />
            <mesh geometry={nodes.Cylinder_6_2.geometry} material={nodes.Cylinder_6_2.material} position={[-67.316, -2.732, -67.325]} rotation={[-Math.PI / 2, -1.484, -1.658]} scale={1.241} />
            <mesh geometry={nodes.Cylinder_4_1.geometry} material={nodes.Cylinder_4_1.material} position={[67.271, -2.732, -67.316]} rotation={[0.086, 0.015, 0.087]} scale={1.241} />
            <mesh geometry={nodes.Cylinder_5_1.geometry} material={nodes.Cylinder_5_1.material} position={[-67.325, -2.732, 67.316]} rotation={[-0.087, 0, -0.087]} scale={1.241} />
            <mesh geometry={nodes.Cylinder_2_3.geometry} material={nodes.Cylinder_2_3.material} position={[3.248, 110.662, 3.319]} scale={1.241} />
          </group>
          <group position={[-47.413, 10.178, 45.323]} rotation={[-2.975, 0.518, 3.058]} scale={[0.642, 0.698, 0.698]}>
            <group position={[3.04, 1.12, -81.16]} rotation={[-Math.PI / 9, 0, 0]} scale={[1.638, 1.508, 1.508]}>
              <mesh geometry={nodes.S.geometry} material={nodes.S.material} position={[-32, -6.5, 0]} />
              <mesh geometry={nodes.p.geometry} material={nodes.p.material} position={[-18.144, -6.5, 0]} />
              <mesh geometry={nodes.l.geometry} material={nodes.l.material} position={[-5.52, -6.5, 0]} />
              <mesh geometry={nodes.i.geometry} material={nodes.i.material} position={[0.08, -6.5, 0]} />
              <mesh geometry={nodes.i_1.geometry} material={nodes.i_1.material} position={[0.08, -6.5, 0]} />
              <mesh geometry={nodes.n.geometry} material={nodes.n.material} position={[5.68, -6.5, 0]} />
              <mesh geometry={nodes.e.geometry} material={nodes.e.material} position={[18.304, -6.5, 0]} />
            </group>
            <mesh geometry={nodes.Rectangle_2_6.geometry} material={nodes.Rectangle_2_6.material} position={[0, -0.214, -81.435]} rotation={[-Math.PI / 9, 0, 0]} />
            <mesh geometry={nodes.Rectangle_5_6.geometry} material={nodes.Rectangle_5_6.material} position={[0, -66.011, 62.638]} rotation={[Math.PI / 2, 0, 0]} scale={0.833} />
            <mesh geometry={nodes.Rectangle_4_3.geometry} material={nodes.Rectangle_4_3.material} position={[0, -62.816, -3.881]} rotation={[Math.PI / 2, 0, 0]} scale={0.833} />
            <mesh geometry={nodes.Rectangle_3_6.geometry} material={nodes.Rectangle_3_6.material} position={[0, -66.851, 15.835]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Rectangle_12.geometry} material={nodes.Rectangle_12.material} position={[0, -5.445, -85.575]} rotation={[-Math.PI / 9, 0, 0]} />
          </group>
          <group position={[5.062, 49.665, -37.851]} rotation={[0, -Math.PI / 6, 0]}>
            <mesh geometry={nodes.line.geometry} material={nodes.line.material} position={[-8.343, -29.822, -1.067]} />
            <mesh geometry={nodes.Cylinder_2_4.geometry} material={nodes.Cylinder_2_4.material} position={[0.965, 83.675, -58.409]} rotation={[0.216, -0.167, 0]} scale={1.334} />
            <mesh geometry={nodes['hand-15_2'].geometry} material={nodes['hand-15_2'].material} position={[57.193, -72.481, 62.327]} rotation={[1.774, 0.04, 0.48]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes['hand-15'].geometry} material={nodes['hand-15'].material} position={[-69.048, -69.333, 71.267]} rotation={[1.814, 0.306, -0.243]} />
            <mesh geometry={nodes.body_1.geometry} material={nodes.body_1.material} position={[0.153, 16.283, -51.267]} />
          </group>
          <group position={[18.506, 200.478, -52.921]} rotation={[0.398, -0.489, 0.195]}>
            <mesh geometry={nodes.Cube_10.geometry} material={nodes.Cube_10.material} position={[29.23, 40.355, 17.521]} rotation={[-0.673, 0.582, -0.072]} scale={[0.967, 0.846, 1]} />
            <mesh geometry={nodes.Cube_11.geometry} material={nodes.Cube_11.material} position={[-4.847, -22.512, 35.868]} />
            <mesh geometry={nodes.Cube_7_1.geometry} material={nodes.Cube_7_1.material} position={[-2.709, 44.726, -69.775]} rotation={[0.611, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Cube_7_2.geometry} material={nodes.Cube_7_2.material} position={[-3.462, -35.76, 36.791]} />
            <mesh geometry={nodes.Cube_3_4.geometry} material={nodes.Cube_3_4.material} position={[-3.714, -39.927, -45.365]} />
            <mesh geometry={nodes.Cube_4_6.geometry} material={nodes.Cube_4_6.material} position={[49.144, -11.334, 15.695]} rotation={[-0.047, -0.34, -0.024]} scale={[-1, 1, 1.141]} />
            <mesh geometry={nodes.Cube_2_7.geometry} material={nodes.Cube_2_7.material} position={[34.854, 14.428, 27.348]} rotation={[0.026, -0.606, 0.136]} scale={[-1, 1, 1.363]} />
            <mesh geometry={nodes.Cube_6_2.geometry} material={nodes.Cube_6_2.material} position={[12.611, 21.847, 28.499]} rotation={[0.372, -0.791, 1.733]} scale={[1, 1, 0.779]} />
            <mesh geometry={nodes.Cube_5_3.geometry} material={nodes.Cube_5_3.material} position={[-45.387, 23.812, 20.24]} rotation={[-0.093, 0.348, -0.483]} />
            <mesh geometry={nodes.Cube_12.geometry} material={nodes.Cube_12.material} position={[-51.456, 1.701, 11.029]} rotation={[-0.093, 0.348, 0.238]} />
            <mesh geometry={nodes.Cube_15.geometry} material={nodes.Cube_15.material} position={[11.672, 1.118, 30.38]} rotation={[0, Math.PI / 9, 0]} />
            <mesh geometry={nodes.Cube_14.geometry} material={nodes.Cube_14.material} position={[-21.34, 1.118, 28.721]} rotation={[0, -Math.PI / 9, 0]} />
            <mesh geometry={nodes.Cube_13.geometry} material={nodes.Cube_13.material} position={[-21.984, 10.292, 29.165]} rotation={[-0.038, -0.411, 3.029]} />
            <mesh geometry={nodes.Cube_12_1.geometry} material={nodes.Cube_12_1.material} position={[12.598, 6.379, 31.351]} rotation={[-0.1, 0.281, 0.204]} />
            <mesh geometry={nodes.Cube_16.geometry} material={nodes.Cube_16.material} position={[38.422, -12.667, -6.069]} scale={[-1, 1, 1]} />
            <mesh geometry={nodes.Cube_17.geometry} material={nodes.Cube_17.material} position={[-44.386, -12.667, -6.069]} />
            <mesh geometry={nodes.Sphere_2.geometry} material={nodes.Sphere_2.material} position={[-2.883, -8.507, -8.675]} />
          </group>
          <mesh geometry={nodes.leg.geometry} material={nodes.leg.material} position={[31.273, -40.935, -83.018]} rotation={[0, -Math.PI / 6, 0]} />
          <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[33.516, 151.868, -85.204]} rotation={[0.398, -0.489, 0.195]} />
        </group>
        <group position={[643.472, 608.805, -737.721]} scale={1.651}>
          <mesh geometry={nodes.Cylinder_4.geometry} material={nodes.Cylinder_4.material} position={[0.247, -107.094, -0.707]} scale={0.854} />
          <mesh geometry={nodes.Cylinder_6.geometry} material={nodes.Cylinder_6.material} position={[-0.155, -65.351, -0.707]} scale={0.854} />
          <mesh geometry={nodes.Cylinder_5.geometry} material={nodes.Cylinder_5.material} position={[-0.155, -149.662, -0.707]} scale={0.854} />
          <mesh geometry={nodes.Cylinder_3.geometry} material={nodes.Cylinder_3.material} position={[-0.532, -212.516, 1.567]} />
          <mesh geometry={nodes.Cylinder_2.geometry} material={nodes.Cylinder_2.material} position={[-0.247, -296.915, 0.707]} />
        </group>
        <group position={[820.649, 713.946, 442.461]}>
          <mesh geometry={nodes.Ellipse_3.geometry} material={nodes.Ellipse_3.material} position={[-2.538, -7.921, 1.445]} rotation={[0, -Math.PI / 2, 0]} scale={0.589} />
          <mesh geometry={nodes.Ellipse_2.geometry} material={nodes.Ellipse_2.material} position={[-2.538, 70.358, 1.445]} rotation={[0, -Math.PI / 2, 0]} scale={0.589} />
          <mesh geometry={nodes.Ellipse.geometry} material={nodes.Ellipse.material} position={[-2.538, 147.533, 1.445]} rotation={[0, -Math.PI / 2, 0]} scale={0.589} />
          <mesh geometry={nodes.Rectangle_5.geometry} material={nodes.Rectangle_5.material} position={[9.477, -26, 0]} rotation={[0, -Math.PI / 2, 0]} />
        </group>
        <group position={[620.145, 554.314, -211.887]} rotation={[0, -Math.PI / 2, 0]} scale={0.707}>
          <mesh geometry={nodes.Triangle_2.geometry} material={nodes.Triangle_2.material} position={[41.469, -49.005, 11.469]} rotation={[0, 0.001, 0]} scale={[1.164, 1.164, 11432065741406.766]} />
          <mesh geometry={nodes.Triangle.geometry} material={nodes.Triangle.material} position={[-100.907, -31.311, 10.859]} rotation={[0, 0.001, 0]} scale={[1.164, 1.164, 11432065741406.766]} />
          <mesh geometry={nodes.Ellipse_1.geometry} material={nodes.Ellipse_1.material} position={[-13.53, 63.176, 9.128]} scale={1.3} />
          <mesh geometry={nodes.Rectangle_6.geometry} material={nodes.Rectangle_6.material} position={[-38.576, 0, -1.015]} scale={0.918} />
          <mesh geometry={nodes.Rectangle_5_1.geometry} material={nodes.Rectangle_5_1.material} position={[-38, 0, -17.875]} />
        </group>
        <group position={[722.772, 745.423, -472.721]} rotation={[0, -Math.PI / 2, 0]} scale={0.621}>
          <mesh geometry={nodes.Ellipse_3_1.geometry} material={nodes.Ellipse_3_1.material} position={[-77.515, 313.592, 4.655]} scale={0.977} />
          <mesh geometry={nodes.Ellipse_2_1.geometry} material={nodes.Ellipse_2_1.material} position={[-127.291, 313.592, 4.655]} scale={0.977} />
          <mesh geometry={nodes.Ellipse_4.geometry} material={nodes.Ellipse_4.material} position={[-178.65, 313.592, 4.655]} scale={0.977} />
          <mesh geometry={nodes.Rectangle_7.geometry} material={nodes.Rectangle_7.material} position={[0, -238.943, 4.003]} />
          <mesh geometry={nodes.Rectangle_9.geometry} material={nodes.Rectangle_9.material} position={[98.234, -16.398, 3.268]} />
          <mesh geometry={nodes.Rectangle_8.geometry} material={nodes.Rectangle_8.material} position={[98.234, 173.681, 3.268]} />
          <mesh geometry={nodes.Rectangle_9_1.geometry} material={nodes.Rectangle_9_1.material} position={[-106.76, -16.398, 3.268]} />
          <mesh geometry={nodes.Rectangle_6_1.geometry} material={nodes.Rectangle_6_1.material} position={[-106.76, 173.681, 3.268]} />
          <mesh geometry={nodes.Rectangle_5_2.geometry} material={nodes.Rectangle_5_2.material} position={[0, 0, -13.469]} />
        </group>
        <group position={[805.649, 559.176, -103.286]} rotation={[0, -Math.PI / 2, 0]} scale={0.656}>
          <group position={[381.081, 121.317, 18.333]} scale={1.006}>
            <mesh geometry={nodes.Cylinder_2_5.geometry} material={nodes.Cylinder_2_5.material} position={[-11.095, 133.571, 0.801]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 1.077, 1]} />
            <mesh geometry={nodes.Cylinder_9.geometry} material={nodes.Cylinder_9.material} position={[-8.64, -133.571, 0.801]} rotation={[0, 0, Math.PI / 2]} scale={[1, 1.077, 1]} />
            <mesh geometry={nodes.Sphere_2_1.geometry} material={nodes.Sphere_2_1.material} position={[122.248, 132.867, 0]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[-141.8, -132.867, 0]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.Cylinder_2_6.geometry} material={nodes.Cylinder_2_6.material} position={[123.294, 0.972, 0.801]} rotation={[0, 0, Math.PI]} />
            <mesh geometry={nodes.Cylinder_10.geometry} material={nodes.Cylinder_10.material} position={[-142.846, -0.972, 0.801]} />
            <mesh geometry={nodes.Sphere_2_2.geometry} material={nodes.Sphere_2_2.material} position={[122.59, -132.867, 0]} rotation={[0, 0, Math.PI]} />
            <mesh geometry={nodes.Sphere_1.geometry} material={nodes.Sphere_1.material} position={[-142.142, 132.867, 0]} />
          </group>
          <group position={[372.711, 159.533, 22.454]} scale={1.524}>
            <mesh geometry={nodes.A.geometry} material={nodes.A.material} position={[-77, -67.5, 0]} />
            <mesh geometry={nodes.a.geometry} material={nodes.a.material} position={[3.91, -67.5, 0]} />
          </group>
          <mesh geometry={nodes.Rectangle_4.geometry} material={nodes.Rectangle_4.material} position={[369.973, -315.354, 5.684]} scale={1.524} />
          <mesh geometry={nodes.Rectangle_3.geometry} material={nodes.Rectangle_3.material} position={[369.973, -225.14, 5.684]} scale={1.524} />
          <mesh geometry={nodes.Rectangle_2.geometry} material={nodes.Rectangle_2.material} position={[410.365, -135.842, 5.684]} scale={1.524} />
          <mesh geometry={nodes.Rectangle_5_3.geometry} material={nodes.Rectangle_5_3.material} position={[-180.728, -40.121, 19.396]} />
          <mesh geometry={nodes.Rectangle_3_1.geometry} material={nodes.Rectangle_3_1.material} position={[0, -44.003, 5.662]} />
          <mesh geometry={nodes.Rectangle_2_1.geometry} material={nodes.Rectangle_2_1.material} position={[0, 0, -23.619]} />
        </group>
        <group position={[688.693, 174.398, 215.397]}>
          <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} position={[6.442, -6.483, 8.588]} rotation={[0.247, -0.089, -0.251]} />
          <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-10.675, -17.782, -10.371]} rotation={[-0.169, -0.045, 0.258]} />
          <mesh geometry={nodes.Cylinder_1.geometry} material={nodes.Cylinder_1.material} position={[-3.344, -58.967, 0]} />
        </group>
        <group position={[542.104, 176.093, -121.141]}>
          <mesh geometry={nodes.Cube_4.geometry} material={nodes.Cube_4.material} position={[120.14, -9.394, -233.331]} />
          <mesh geometry={nodes.Cube_3.geometry} material={nodes.Cube_3.material} position={[120.14, -9.394, 233.306]} />
          <mesh geometry={nodes.Cube_4_1.geometry} material={nodes.Cube_4_1.material} position={[3.727, -4.744, -233.331]} rotation={[0, 0, -1.222]} />
          <mesh geometry={nodes.Cube_2_1.geometry} material={nodes.Cube_2_1.material} position={[3.727, -4.744, 233.306]} rotation={[0, 0, -1.222]} />
          <mesh geometry={nodes.Cube_4_2.geometry} material={nodes.Cube_4_2.material} position={[7.631, -63.454, -233.331]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_1.geometry} material={nodes.Cube_1.material} position={[7.631, -63.454, 233.306]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle_2_2.geometry} material={nodes.Rectangle_2_2.material} position={[-3.716, 19.963, 0]} rotation={[-Math.PI / 2, -Math.PI / 9, -Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle.geometry} material={nodes.Rectangle.material} position={[3.42, 0.357, 0]} rotation={[-Math.PI / 2, -Math.PI / 9, -Math.PI / 2]} />
        </group>
        <group position={[-603.711, 658.285, -849.623]}>
          <mesh geometry={nodes.Ellipse_5.geometry} material={nodes.Ellipse_5.material} position={[37.993, -12.892, 10.735]} rotation={[0, 0, -Math.PI / 2]} scale={0.938} />
          <mesh geometry={nodes.Shape_4.geometry} material={nodes.Shape_4.material} position={[85.83, -28.037, 8.201]} scale={0.938} />
          <mesh geometry={nodes.Shape_3.geometry} material={nodes.Shape_3.material} position={[-36.244, 174.262, 8.108]} scale={0.938} />
          <mesh geometry={nodes.Shape_2.geometry} material={nodes.Shape_2.material} position={[-105.458, 111.353, 7.972]} scale={0.938} />
          <mesh geometry={nodes.Shape.geometry} material={nodes.Shape.material} position={[-101.045, 111.985, 7.182]} scale={0.938} />
          <mesh geometry={nodes.Rectangle_1.geometry} material={nodes.Rectangle_1.material} position={[0, 0, 2.984]} scale={0.938} />
          <mesh geometry={nodes.Rectangle_3_2.geometry} material={nodes.Rectangle_3_2.material} position={[0, 0, -17.527]} />
        </group>
        <group position={[666.58, 205.463, 370.496]} rotation={[0, -0.175, -0.262]}>
          <mesh geometry={nodes.Shape_3_1.geometry} material={nodes.Shape_3_1.material} position={[-10.484, -28.603, -16.279]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Shape_2_1.geometry} material={nodes.Shape_2_1.material} position={[-10.746, 72.862, -24.099]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Shape_1.geometry} material={nodes.Shape_1.material} position={[-12.404, 52.271, -29.373]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Rectangle_2_3.geometry} material={nodes.Rectangle_2_3.material} position={[-9.93, 0, 0]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Rectangle_3_3.geometry} material={nodes.Rectangle_3_3.material} position={[55.06, -11.51, 7.124]} rotation={[Math.PI / 2, -0.873, Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle_10.geometry} material={nodes.Rectangle_10.material} position={[4.404, 0, 0]} rotation={[0, -Math.PI / 2, 0]} />
        </group>
        <group position={[128.996, 617.5, -853.888]}>
          <mesh geometry={nodes.Cube_4_3.geometry} material={nodes.Cube_4_3.material} position={[0.635, 0.937, -10.808]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_5.geometry} material={nodes.Cube_5.material} position={[1.686, 105.584, 0]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.窗户.geometry} material={nodes.窗户.material} position={[0, 0, 9.159]} rotation={[0, 0, -Math.PI / 2]} />
        </group>
        <group position={[478.178, 52.425, 781.078]} rotation={[0, 0.405, 0]} scale={0.752}>
          <mesh geometry={nodes.Cube_2_2.geometry} material={nodes.Cube_2_2.material} position={[15.328, 90.953, -1.224]} rotation={[0, Math.PI / 4, 0]} />
          <mesh geometry={nodes.Cube_3_1.geometry} material={nodes.Cube_3_1.material} position={[-21.328, 13.101, 36.975]} rotation={[-3.054, -Math.PI / 4, -3.054]} scale={1.046} />
          <mesh geometry={nodes.Cube_4_4.geometry} material={nodes.Cube_4_4.material} position={[37.567, -65.585, -107.001]} rotation={[-0.044, 1.223, -0.219]} />
          <mesh geometry={nodes.Cube_5_1.geometry} material={nodes.Cube_5_1.material} position={[-12.894, -31.138, 51.834]} rotation={[-3.113, 1.3, -2.907]} scale={1.046} />
          <mesh geometry={nodes.Cube_6.geometry} material={nodes.Cube_6.material} position={[17.446, -42.096, 91.53]} rotation={[0, -1.222, -0.175]} />
          <mesh geometry={nodes.Ellipse_3_2.geometry} material={nodes.Ellipse_3_2.material} position={[6.874, -137.161, 1.303]} rotation={[-Math.PI / 2, 0, -1.976]} scale={1.543} />
          <mesh geometry={nodes.Plant_Base.geometry} material={nodes.Plant_Base.material} position={[13.953, -371.942, 0.557]} rotation={[-Math.PI / 2, 0, 0]} scale={1.668} />
        </group>
        <group position={[-770.834, -194.216, -624.268]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Cube_3_2.geometry} material={nodes.Cube_3_2.material} position={[13.159, -22.511, -7.555]} rotation={[-0.605, 0.045, 2.884]} scale={2.529} />
          <mesh geometry={nodes.Cube_2_3.geometry} material={nodes.Cube_2_3.material} position={[28.142, 5.347, 39.881]} rotation={[0.343, -0.123, 2.814]} scale={2.529} />
          <mesh geometry={nodes.Cube_7.geometry} material={nodes.Cube_7.material} position={[-45.977, -8.653, 19.745]} rotation={[0.014, -0.006, -2.792]} scale={2.529} />
          <mesh geometry={nodes.Ellipse_6.geometry} material={nodes.Ellipse_6.material} position={[-1.56, -20.776, 5.1]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_8.geometry} material={nodes.Cube_8.material} position={[-4.155, -47.238, 4.527]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
        </group>
        <group position={[-473.149, 200.524, -517.548]} rotation={[-0.313, -0.594, -0.132]}>
          <group position={[-2.452, 124.233, 31.488]} rotation={[0.262, 0, 0]}>
            <mesh geometry={nodes.Shape_8.geometry} material={nodes.Shape_8.material} position={[78.909, -222.976, 65.085]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Shape_7.geometry} material={nodes.Shape_7.material} position={[160.245, 193.088, -50.272]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Shape_6.geometry} material={nodes.Shape_6.material} position={[105.303, 217.945, -51.779]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Shape_5.geometry} material={nodes.Shape_5.material} position={[-165.44, -26.034, 8.156]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Shape_3_2.geometry} material={nodes.Shape_3_2.material} position={[-164.096, -59.184, 17.481]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Shape_2_2.geometry} material={nodes.Shape_2_2.material} position={[-164.352, -59.806, 18.46]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Shape_9.geometry} material={nodes.Shape_9.material} position={[-163.825, -120.705, 36.171]} rotation={[-0.262, 0, 0]} scale={0.946} />
            <mesh geometry={nodes.Rectangle_2_7.geometry} material={nodes.Rectangle_2_7.material} position={[0, 0, -0.051]} rotation={[-0.262, 0, -Math.PI / 2]} scale={0.946} />
            <mesh geometry={nodes.Rectangle_13.geometry} material={nodes.Rectangle_13.material} position={[0, 0, 0.526]} rotation={[-0.262, 0, -Math.PI / 2]} scale={0.946} />
          </group>
          <mesh geometry={nodes.Cube_5_2.geometry} material={nodes.Cube_5_2.material} position={[-1, 125.367, 14.486]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_6_1.geometry} material={nodes.Cube_6_1.material} position={[2.488, -110.743, -215.131]} rotation={[Math.PI / 6, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_4_5.geometry} material={nodes.Cube_4_5.material} position={[2.488, -180.051, 19.571]} />
          <mesh geometry={nodes.Cube_3_3.geometry} material={nodes.Cube_3_3.material} position={[2.488, 164.407, -19.571]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Cube_2_4.geometry} material={nodes.Cube_2_4.material} position={[118.678, -139.907, -19.571]} rotation={[0, 0, -1.396]} />
          <mesh geometry={nodes.Cube_9.geometry} material={nodes.Cube_9.material} position={[-107.203, -134.706, -19.571]} rotation={[0, 0, -1.745]} />
        </group>
        <group position={[618.829, -107.953, -266.726]} scale={0.702}>
          <mesh geometry={nodes.Cylinder_3_1.geometry} material={nodes.Cylinder_3_1.material} position={[262.369, -38.318, -709.39]} />
          <mesh geometry={nodes.Cylinder_2_1.geometry} material={nodes.Cylinder_2_1.material} position={[262.369, -38.318, 862.796]} />
          <mesh geometry={nodes.Cylinder_3_2.geometry} material={nodes.Cylinder_3_2.material} position={[-249.048, -35.665, -709.39]} />
          <mesh geometry={nodes.Cylinder_7.geometry} material={nodes.Cylinder_7.material} position={[-249.048, -38.318, 862.796]} />
          <mesh geometry={nodes.Rectangle_11.geometry} material={nodes.Rectangle_11.material} position={[0, 230.159, 91.5]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
        </group>
        <group position={[-177.841, -318.388, 98.398]}>
          <mesh geometry={nodes.Ellipse_2_2.geometry} material={nodes.Ellipse_2_2.material} position={[0, 7.389, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.086, 1.086, 1.661]} />
          <mesh geometry={nodes.Ellipse_7.geometry} material={nodes.Ellipse_7.material} position={[0, -7.389, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[1.086, 1.086, 1.661]} />
        </group>
        <directionalLight intensity={0.7} decay={2} rotation={[1.203, 0.512, -1.385]} target={nodes.Directional_Light.target}>
          <primitive object={nodes.Directional_Light.target} position={[0, 0, -1]} />
        </directionalLight>
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[-3662.89, 2379.989, 3678.248]} rotation={[-0.539, -0.715, -0.374]} />
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[-3200.106, 2496.747, 4076.364]} rotation={[-0.539, -0.715, -0.374]} />
        <mesh geometry={nodes.Walls.geometry} material={nodes.Walls.material} position={[33.168, -323.764, -23.547]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.702} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/mini_room_art_copy.glb')
